### ISSUE TITLE
How to quickly obtain offset by oneself 

### ISSUE THREAD

**Issue by IDhammaI** [sezzyaep/CS2-OFFSETS#3]
I really want to learn how to obtain them on my own. Waiting for you to update may take some time. I hope you can teach us!

**Comment by iqrw0** [comment]
This is literally just https://github.com/a2x/cs2-dumper with his cheat name slapped on it. lmao

**Comment by sezzyaep** [comment]
You can check 

https://github.com/a2x/cs2-dumper

for more info
